[package]
name = "aoel-parser"
version = "0.1.0"
edition = "2021"
description = "AOEL Parser"

[dependencies]
thiserror = "1.0"
aoel-lexer = { path = "../aoel-lexer" }
aoel-ast = { path = "../aoel-ast" }
