[package]
name = "vais-types"
version.workspace = true
edition.workspace = true

[dependencies]
vais-ast = { path = "../vais-ast" }
vais-i18n = { path = "../vais-i18n" }
thiserror = { workspace = true }
miette = { workspace = true }
colored = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
vais-parser = { path = "../vais-parser" }
