[package]
name = "vais-types"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Type checker and inference engine for the Vais programming language"

[dependencies]
vais-ast = { path = "../vais-ast" }
vais-i18n = { path = "../vais-i18n" }
thiserror = { workspace = true }
miette = { workspace = true }
colored = { workspace = true }
rayon = "1.10"

[dev-dependencies]
pretty_assertions = { workspace = true }
vais-parser = { path = "../vais-parser" }
