[package]
name = "vais-ast"
version.workspace = true
edition.workspace = true
description = "Vais Abstract Syntax Tree"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
vais-lexer = { path = "../vais-lexer" }

[dev-dependencies]
serde_json = "1.0"
