[package]
name = "vais-ast"
version = "1.0.0"
edition = "2021"
description = "Vais Abstract Syntax Tree"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
vais-lexer = { path = "../vais-lexer" }

[dev-dependencies]
serde_json = "1.0"
