[package]
name = "vais-parser"
version.workspace = true
edition.workspace = true
description = "Vais Parser"

[dependencies]
thiserror = "1.0"
vais-lexer = { path = "../vais-lexer" }
vais-ast = { path = "../vais-ast" }
