[package]
name = "vais-lowering"
version.workspace = true
edition.workspace = true
description = "Vais AST to IR lowering"

[dependencies]
vais-ast = { path = "../vais-ast" }
vais-lexer = { path = "../vais-lexer" }
vais-ir = { path = "../vais-ir" }
thiserror = "2.0"
serde = { workspace = true }
serde_json = "1.0"
bincode = "1.3"

[dev-dependencies]
vais-parser = { path = "../vais-parser" }
