[package]
name = "vais-lowering"
version = "1.0.0"
edition = "2021"
description = "Vais AST to IR lowering"

[dependencies]
vais-ast = { path = "../vais-ast" }
vais-lexer = { path = "../vais-lexer" }
vais-ir = { path = "../vais-ir" }
thiserror = "2.0"

[dev-dependencies]
vais-parser = { path = "../vais-parser" }
