[package]
name = "aoel-typeck"
version.workspace = true
edition.workspace = true
description = "AOEL Type Checker"

[dependencies]
aoel-ast = { workspace = true }
aoel-lexer = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
aoel-parser = { workspace = true }
